### ISSUE TITLE
Error importing @monerium/sdk

### ISSUE THREAD

**Issue by podefr** [monerium/js-monorepo#76]
Hi team,

Since upgrading `@monerium/sdk` to version `2.13.1` I'm running into this issue:

```
import { MoneriumClient } from "@monerium/sdk";
```

throws this error:

```
] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.../node_modules/crypto-js/enc-base64url' imported from /.../node_modules/@monerium/sdk/dist/index.mjs
[0] Did you mean to import "crypto-js/enc-base64url.js"?
```

I would expect it to just "work" as it did before.

Here's my `tsconfig.json`:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": ["@tsconfig/node20/tsconfig.json"],
  "compilerOptions": {
    "outDir": "build",
    "resolveJsonModule": true,
    "experimentalDecorators": true
  },
  "include": ["src"]
}

```

in my package.json I have

```
"type": "module"
```

Given my configuration, it loads the `index.mjs` file which is correct, but the `.mjs` file imports files without the `.js` extension:

```
import z from 'crypto-js/enc-base64url';
import F from 'crypto-js/sha256';
```

which is not standard and I believe causes my error.
the built files should have imports with the `.js` extension. 

When adding the `.js` extension the error disappears but then for some reason it just outputs the content of the file, so not sure what else is broken.

Would you have any idea? Could my configuration be wrong (although it worked fine with `2.11`).

thanks!

**Comment by einaralex** [comment]
This should no longer be an issue, resolved here: https://github.com/monerium/js-monorepo/commit/c4fe4a7aa6e4691e65550aa0d5ac7a00c6cdd2e3

Working from `v2.13.3`
